<program> ::= ( <node_definition> | <type_definition> )*

<type_definition> ::= <type_declaration> "=" <type_implementation>
<type_declaration> ::= "type" <type_name>
<type_implementation> ::= "{" ( <field_definition> )* "}" | <type>
<field_definition> ::= <field_name> ":" <type_implementation> ";"

<node_definition> ::= <node_attribute>* <node_declaration> "=" <node_implementation>
<node_declaration> ::= "node" <node_name> "(" <port_definition>* ")" "=>" "(" <port_definition>* ")"
<port_definition> ::=  <port_attribute>* <field_name> ":" <type_implementation> ","

<port_attribute> ::= "@optional" | "@required" | "@trigger" <node_name>
<node_attribute> ::= "@export" <string_literal>

<node_implementation> ::= "{" ( <statement_definition> )* "}" | "@import" <string_literal>
<statement_definition> ::= <node_instance> | <node_connection>

<node_instance> ::= "let" <field_name> ":" <node_name> ";"

<node_connection> ::= <field_access> "<-" <field_access> ";"
<field_access> ::= <field_name> ("." <field_name>)*

<type> ::= <primitive_type> | <type_name>
<primitive_type> ::= "i64" | "i32" | "i16" | "i8" | "u64" | "u32" | "u16" | "u8" | "string" | "f32" | "f64" | "bool"

<type_name> ::= ...
<field_name> ::= ...
<node_name> ::= ...

<string_literal> = """ <letter>* """
<number_literal> = ...
<character_literal> = ...
<bool_literal> = true | false